version: "3.9"

services:

  demo:
    build: 
      context: ./src
    container_name: demo_pyroscope
    ports:
      - 8000:80
    environment:
      - PYROSCOPE_APPLICATION_NAME=demo.profiling
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
    networks:
      - demo

  pyroscope:
    container_name: pyroscope
    image: pyroscope/pyroscope:latest
    command:
      - server
    ports:
      - 4040:4040
    deploy:
      resources:
        limits:
          memory: 300M
    restart: always
    networks:
      - demo      

networks:
  demo:
    driver: bridge    
